### ISSUE TITLE
define a specific namespace when running jmeter tests?

### ISSUE THREAD

**Issue by nik-afa** [hellofresh/kangal#176]
Hi guys, thank you for cool project!

One questions, when running tests, a new namespace with a random name is always created, this is not always convenient, since there is no way to limit the namespace by CPU and memory resources ...
Is it possible to define a specific namespace when running jmeter tests?

**Comment by s-radyuk** [comment]
Hello @nik-afa and thank you for your attention to Kangal!

This is by design that Kangal creates a new namespace with a random name for every new load test. And we have a way to limit CPU and memory resources per pod using environment variables. You can specify them when running Kangal-controller process. Environment variables depend on the load-test backend you're using.

1. For JMeter: https://github.com/hellofresh/kangal/blob/master/docs/env-vars.md#jmeter

- JMETER_MASTER_CPU_LIMIT
- JMETER_MASTER_CPU_REQUESTS 
- JMETER_MASTER_MEMORY_LIMITS 
- JMETER_MASTER_MEMORY_REQUESTS 
- and same for JMETER_WORKER_...

2. For Locust https://github.com/hellofresh/kangal/blob/master/docs/env-vars.md#locust
3. For ghz https://github.com/hellofresh/kangal/blob/master/docs/env-vars.md#ghz

If you're running Kangal with helm you can specify the limits in [values.yaml](https://github.com/hellofresh/kangal/blob/master/charts/kangal/values.yaml#L168)

This will allow you to limit the total resources per every loadtest namespace.
I hope it will help you to solve your problem.

**Comment by nik-afa** [comment]
@s-radyuk Thx for response!

Yes, I used vars JMETER_MASTER_CPU_LIMIT and other, and node selector https://github.com/hellofresh/kangal/issues/142

However, I need the ability to specify the namespace name, for additional control, I understand that this is by design, maybe there is possible to get around this?

**Comment by s-radyuk** [comment]
There's no workaround for this case but you can build and use your local version of Kangal with a small hardcoded change in [loadtest.go](https://github.com/hellofresh/kangal/blob/master/pkg/kubernetes/apis/loadtest/v1/loadtest.go#L27). You can replace `generatedName` with something you want, like:
```name := "loadtest-" + "my-static-name"```
This will make Kangal create loadtests and namespaces with the same name "loadtest-my-static-name". Be careful, with this change you can have only one loadtest at the time.

**Comment by nik-afa** [comment]
@s-radyuk Thx! 
I just used separate kubernetes cluster
