### ISSUE TITLE
hellofresh/kangal images not updated?

### ISSUE THREAD

**Issue by thiagoarrais** [hellofresh/kangal#182]
I've noticed that the kangal images on [docker hub](https://hub.docker.com/r/hellofresh/kangal/tags) are pretty old even though there was a 2.0.10 release recently. Are newer images being published somewhere else?

Maybe related to that: when installing via helm to a brand new cluster, I get pods with `imageID: docker.io/hellofresh/kangal@sha256:8b64b247581[...]`. Which is the ID for version 1.2.0 according to docker hub. If the images are somewhere else, maybe the helm charts need updating?

**Comment by lucasmdrs** [comment]
Hi @thiagoarrais  :wave: 

Thank you for your question!

This repository is used to host the Kangal application and serve as the Kangal Helm Chart repository too.
The releases are used to specify the Helm Chart version as well as the application version, the key differences are:
 - Helm Chart versions are tagged as `kangal-a.b.c`
 - Kangal versions are tagged as `x.y.z`
 
 Both follow the semantic versioning but for different things. As of now, Kangal latest version is [`1.2.0`](https://github.com/hellofresh/kangal/releases/tag/1.2.0) and the latest chart version of Kangal is [`2.0.10`](https://github.com/hellofresh/kangal/releases/tag/kangal-2.0.10)
 
We had some discussions about splitting the chart from this repository, but that has not yet been decided.

With all that being said, you remain correct! It's being a while since we released a new version for Kangal, but we plan to release it real soon (this week) :eyes: 
With all the nice contributions we received recently. :sparkles: :heart_eyes:  

I hope that clarifies things a bit and apologize for the delayed release cycle.

**Comment by thiagoarrais** [comment]
I think I got it. Thanks for the response.
