### ISSUE TITLE
There is a conflict with loadtest between datastore and cache

### ISSUE THREAD

**Issue by nik-afa** [hellofresh/kangal#202]
Hi guys, what does this controller error mean? I run the test, and see this error every time

`datastore
E0222 08:42:22.954016 1 loadtest.go:428] there is a conflict with loadtest 'loadtest-right-seal' between datastore and cache. it might be because object has been removed or modified in the datastore
`

**Comment by lucasmdrs** [comment]
Hi there @nik-afa :wave: 

Thank you for raising this question.This error happens when the state of the `LoadTest` resource changed while the sync handler is running.

The [sync handler](https://github.com/hellofresh/kangal/blob/1bc3a4c8eeae3a995c735e6789de4bb459d68d5a/pkg/controller/loadtest.go#L276) is the function responsible for getting the `LoadTest` resources and updating their information based on the their backend. If in the meantime, the resource changes, it will fail to apply the new information and raise the error that you mentioned.

There could be many reasons for this to happen, including but not limited to: 
 - A hook/operator in the cluster that made some change in it due to an event :robot: 
 - Manual change done by a human :construction_worker: 
 - Duplicate controller running in the cluster. :busts_in_silhouette: 

I hope that clarifies the error a bit, let me know if you have any other questions :slightly_smiling_face:

**Comment by nik-afa** [comment]
Thx for speedy response! I use helm chart for install Kangal and and choised in values two replicas for controller, may be i need decrease number of replicas?

**Comment by nik-afa** [comment]
One more question, i noticed that for the workers, the jmeter in the base image is specified as heap size, how can this be respecified?
`ENV HEAP -Xms2g -Xmx2g -XX:MaxMetaspaceSize=256m`
https://github.com/hellofresh/kangal-jmeter/blob/2aa2f3da489af689f6720dbaca1b526cab0e7cc7/docker/jmeter-base/Dockerfile#L13

**Comment by lucasmdrs** [comment]
> I use helm chart for install Kangal and and choised in values two replicas for controller, may be i need decrease number of replicas?

Yes, currently if you run two controllers they will compete each other to sync resources.

> the jmeter in the base image is specified as heap size, how can this be respecified?

You should be able to add or overwrite environment variables in the worker images by passing a file in the `envVars` form field when creating load tests, check our [docs](https://github.com/hellofresh/kangal/blob/0f7355991f5dc8c32b370f4d9537e21307817032/docs/user-flow.md#using-jmeter) for some examples

**Comment by nik-afa** [comment]
thanks!
