### ISSUE TITLE
Improving OpenAPI definition

### ISSUE THREAD

**Issue by olvlvl** [hellofresh/kangal#21]
Hi everyone,

The OpenAPI definition doesn't include descriptions or examples for the parameters and schemas, which makes using the API quite difficult. For example, what are the expectations for `testData` and `testFile` in `#/components/schemas/LoadTest`?

I read ["How to use Kangal"](https://github.com/hellofresh/kangal/blob/master/docs/README.md#how-do-i-use-kangal) and ["Kangal User Flow"](https://github.com/hellofresh/kangal/blob/master/docs/Kangal-user-flow.md), I there's no example in there either.

```
curl -X POST http://${KANGAL_PROXY_ADDRESS}/load-test \
  -H 'Content-Type: multipart/form-data' \
  -F distributedPods=1 \
  -F testFile=@./examples/constant_load.jmx \
  -F testData=@./artifacts/loadtests/testData.csv \
  -F envVars=@./artifacts/loadtests/envVars.csv \
  -F type=JMeter
```

An example of `testData.csv` and `envVars.csv` would help.

*Edit*: I found `testData.csv` and `envVars.csv` in `artifacts/loadtests`. I can guess how to use `envVars.cvs`, but what's the layout for `testData.csv`?

**Comment by s-radyuk** [comment]
Hello Olivier,

Thank you a lot for your feedback! And a special thanks for the attention to our documentation, we appreciate it.

In [Kangal user flow](https://github.com/hellofresh/kangal/blob/master/docs/Kangal-user-flow.md#create) you can see the note saying this example CURL command is specific for JMeter load generator type and for other types the data can be different. That's why the fields `testData` and `envVars` are optional for the POST request. You can leave them empty.

When users want to use JMeter as a load generator we expect them to go through this doc [How to write and understand a JMeter test](https://github.com/hellofresh/kangal/blob/master/docs/jmeter-in-kangal/How-to-write-tests.md#tests-with-test-data). It has an explanation of testData and envVars files, why they are needed for JMeter test, and how to create them. Do you think it would help if we add the link to this doc to the OpenAPI definition?
